### ISSUE TITLE
Documented vulnerability

### ISSUE THREAD

**Issue by jonathanpmartins** [phpecc/phpecc#112]
Like it is mention on the Docs "one documented vulnerability", i would like to know more about it. Do you guys have some links or more information about this vulnerability, and how I can get around it?
@mdanter @btcdrak @afk11 @aztech-dev

**Comment by afk11** [comment]
This was the point multiplication algorithm, discussed here https://github.com/phpecc/phpecc/issues/16 The concern was the library could leak information about the private key via side channels.

A subsequent issue was found, in that multiplication and addition wasn't constant time. The fix has yet to be merged actually, but the solution is probably easy to miss in the PR: https://github.com/aztech-forks/php-ecc/commit/f87418c0793f5ef8a367bd3554754c2b80e0b198#diff-36a91cb81a4baa065069998d1bcf810cL268 There needed to be as many bits in the string as the key size, otherwise there was a time dependence for the multiplication operation. 

Both had no effect on the results produced by the library, but they are implementation specific nits that can leak information about the key.

**Comment by jonathanpmartins** [comment]
I´m trying to implement web push notifications for firefox, and I need something to encrypt my payload with ECDH. I saw other libs, made in javascript for node, python, etc... but my project uses PHP. I like to stand with it.
@afk11 Can you confirm if it is secure to use this lib even is my connections are secure (https).

**Comment by afk11** [comment]
I avoid absolute terms to describe software security, because it's never that simple. 

Checking the first link above: we know the double-add-always is

**Comment by marco-c** [comment]
@jonathanpmartins you might want to look at https://github.com/Minishlink/web-push/pull/1.

**Comment by afk11** [comment]
This was fixed in master, we're expecting a tagged release with it soon. 

@jonathanpmartins That's not a guarantee you should accept from someone over the internet - I don't know what you're doing :) Generally speaking, we've placed emphasis on safety/correctness over speed, and some of the more crucial parts have undergone paid review by crypto experts. 

That said, it's not impossible for an implementation slip to introduce a weakness. It doesn't break the library, but may pose problems depending on what your threat model is.
