### ISSUE TITLE
CVE-2015-7940

### ISSUE THREAD

**Issue by Spomky** [phpecc/phpecc#192]
Hi,

I read about a [critical issue from the bouncycastle](https://blogs.adobe.com/security/2017/03/critical-vulnerability-uncovered-in-json-encryption.html) library that allows an attacker to create malicious Json Web Token by using points on an invalid curve.

The JWT library I maintain is based on this library to perform encryption/decryption based on the ECDH-ES algorithm. [I added some tests and it seems it is immuned](https://github.com/Spomky-Labs/jose/commit/af3a88fc33eb51fde812ee42431cfa8fe2fdf35c).

I would like to be sure that this library verifies if the point of the public key is on the same curve as the one of the private key.

**Comment by afk11** [comment]
I took a while yesterday evening to check this out. It seems the Point class checks the coordinates exist on the curve in the constructor, and also verifies each intermediate point during scalar multiplication is valid (because of the constructor check), with an explicit call to validate after the product is created. 

I'll add a test case for the invalid point, not sure yet how to test the invalid scalar mult.

**Comment by afk11** [comment]
Looking at this again, wish I did this sooner: https://github.com/phpecc/phpecc/pull/216
