### ISSUE TITLE
Not sure if this is correct or not?

### ISSUE THREAD

**Issue by Fomtriok** [phpecc/phpecc#226]
I am a student and I am trying out your marvellous library purely for learning purposes.

In HmacRandomNumberGenerator, in the array on line 40 it says 'sha384' => 385. Should that be 385? Just asking, because to my untrained eye, that number didn't fit the symmetry of the rest. (But then I don't know about the specifics of the algorithm.)

A second small thing. In the Readme, it says "secg256r1" and "secg384r1", but aren't the names of the algorithms secp?

(If I could just add a small more "personal" question: What hash algorithm would be most natural to use for SignHasher in combination with secp384r1? Thankful for any recommendation.)

**Comment by afk11** [comment]
Hi, sorry I looked into this at the time and started writing a response! I apologize, I must never have sent it! 

You are totally right! The bug in HmacRandomNumberGenerator _luckily_ isn't triggered because the incorrect bits are shifted out, but indeed, if the higher bits were incorrect then this would lead to deterministic signatures that aren't reproducable except for this implementation.. Thanks for catching this in any case!

Uhm, yes it seems you are right - quick googling seems to show us as the only project claiming support for those curves :P So I think we should fix that too. 

I'd generally match the curve bit length, so SHA384 with secp384r1, and so on.

**Comment by Fomtriok** [comment]
Thanks for your help! Then I'll match it with SHA384.
