### ISSUE TITLE
How to get pulickey from a given privatekey?

### ISSUE THREAD

**Issue by yupnano** [phpecc/phpecc#244]
Hi , I am wondering how to generate a publickey if I only have a privateKey?

By the example code within #177 , we need to create $adapter and $generator , which already decides the pievatekey value. The question is that how could I use a given private key to generate publickey, not to create a new private key and then a publick key.

Thank you for any infromation!

**Comment by afk11** [comment]
https://github.com/phpecc/phpecc/blob/7c77251d3a7f52ef4ebc1c023452aad96ab13c83/tests/unit/Curves/SpecBasedCurveTest.php#L157
This shows how to create the public key object from a private key. Assuming your private key is in hex, you need to init with 16 instead of 10.

I presume you mean you want the serialized public key: https://github.com/phpecc/phpecc/blob/7c77251d3a7f52ef4ebc1c023452aad96ab13c83/tests/unit/Curves/SpecBasedCurveTest.php#L174

**Comment by afk11** [comment]
damn, the line numbers I refered to have since changed :)

https://github.com/phpecc/phpecc/blob/9c69f721fe394d129be8f4461a5b8bfaf2f8a0e4/src/Primitives/GeneratorPoint.php#L103
