### ISSUE TITLE
A couple of learner questions

### ISSUE THREAD

**Issue by dashmccready** [phpecc/phpecc#267]
Hi 🙂, I am trying to learn a bit about public-key cryptography and I am looking into your library for that purpose. Thus, pardon my novice questions. What I am trying to figure out is:

What is the relationship between the $secretMultiplier and the private key?

In detail I mean to ask: Is a pair of the two always static to one another, or does the $secretMultiplier change even though the private key is the same? I am asking because: Could one technically save only the $secretMultiplier instead of the private key, and use it to make an instance of the private key upon each use? (Or _is_ the $secretMultiplier even the private key somehow?)

As a method for trying to figure it out, I generated keys with the secp256k1 curve, and converted the $secretMultiplier to hexadecimal format. Then it was 64 characters long, just like bitcoin keys are supposed to be. Thus I am inclined to believe the $secretMultiplier is the private key, but I would be very appreciative I someone corrected me if it is wrong.

Thank you for your patience and help.
/ Dash

**Comment by afk11** [comment]
> What is the relationship between the $secretMultiplier and the private key?

They're one and the same!

You have a generator point G, a public constant for a selected curve.
You have a private key, k - a 'scalar' number. 
And you have the scalar multiplication algorithm, Q=k*G. This produces a new point as a result, and given Q and G, solving for k is a hard problem (elliptic curve discrete logarithm problem)

**Comment by dashmccready** [comment]
Thank you for your response! And for your overview of the encryption stages/parameters as well. I will save it as a short reference. Have a great day.

**Comment by dashmccready** [comment]
Hi afk11, hope you are doing well. I wondered if I could ask another question.

When $useDerandomizedSignatures is true, does that mean the signature (and the k value) are the same when the same message is signed? And are there any security risks related to that, or is it common to do?

Since the k value is so very large, I figure it would be incredibly unlikely that it would randomly be used again (with useDerandomizedSignatures being false). I am just trying to figure out which option is most safe to choose. :)

**Comment by afk11** [comment]
> When $useDerandomizedSignatures is true, does that mean the signature (and the k value) are the same when the same message is signed?

Yea I think i remember that example, yea it'd return a deterministic K generator as opposed to a completely random

> And are there any security risks related to that, or is it common to do?

I think potential issues depend more on how your application uses keys (even the environment the code runs on)

> Since the k value is so very large, I figure it would be incredibly unlikely that it would randomly be used again

The idea behind derandomizing the k value is because if there the CSPRNG is buggy, and someone has two signatures with the same k value (but even signing two different messages) they can rearrange the ECDSA equations and solve for the private key. This happened in bitcoin a couple of times, the most notable occasion was when the Android OS CSPRNG had low entropy, and some transactions reused k values in their signatures. (people lost bitcoins over it)

I'm not a cryptographer though, so I do suggest you google derandomized ECDSA in the context of certain protocols and see the discussion around it.

**Comment by dashmccready** [comment]
I see. Thank you for your answer to the questions! And for taking your time to elaborate and even give an example of what risks a randomized signature could imply.

I will follow your advice and google derandomized ECDSA then, and read more.

Have a good one!

**Comment by afk11** [comment]
Cheers, you too!

**Comment by afk11** [comment]
Gonna close this now, open a new issue if anything comes up :)
