### ISSUE TITLE
Move project to it's own Github group

### ISSUE THREAD

**Issue by dol** [phpecc/phpecc#97]
The current owner of the Github repository is @mdanter. For a sustainable future of the project I recommend moving the composer prefix and Github project to it's own group. An example is the https://github.com/phpseclib project.

**Comment by afk11** [comment]
No harm, and nothing preventing you from doing so regardless. I'd like if this project got more attention, it's a gem that has saved me a lot of work. 

I have some plans (PGP!) for when I get some spare time, but it would be great to have more review here. I've been trying some tricks for a constant-time base conversion (see Point::mul() - our biggest bottleneck) that would at least stop us leaking the private key. The more accessible this project is, better chance someone else will get to fix it :)

**Comment by aztech-dev** [comment]
@afk11 unrelated to the issue, but isn't Point::mul constant time already ? Unless there's a flaw in the current implementation, that problem is supposed to be resolved...

**Comment by afk11** [comment]
@aztech-dev the loop with the conditional swap, I haven't checked that part. It seems before it gets to that, there's a base_convert call, since you need the individual bits for the algorithm. It's this call that leaks the information. 

I think we can probably do some bitwise operations to make that part constant time too.. I just haven't landed on it yet

**Comment by aztech-dev** [comment]
Erf... the GMP implementation isn't constant time ?

**Comment by aztech-dev** [comment]
Allright, I'll have a look tonight also. But we should probably open a different issue for that :)

**Comment by mdanter** [comment]
All the contributors have done a great job on improving this library. I take a look at pull requests and issues from time to time, but at the moment I'm removed from the PHP community for the most part. If @afk11 or the others think it would receive more attention in its own group I support the initiative.

**Comment by btcdrak** [comment]
Github organisations (referred to as "groups" by OP) do make for more flexibility in terms of administration because there is more fine grained user control (Owner, admin and push). As it stands only mdanter can add/remove people from push access. That's less important because we operate a collaborator workflow which demands pull requests, but certainly if @mdanter and I were to both disappear, the repository would have to move.

What I do not agree with is the idea that moving the project location will improve visibility. Marketing is no substitute.

@mdanter If you want to move this repository to an organisation you have to create a new user, then convert to organisation. You can then push this repo. We'll have to upgrade packagist accordingly as the git URL will change. You can email me at btcdrak at gmail dot com if you want to liaise more.

Regardless of how we move forward, the current collaborator workflow should not be changed. A project of this complexity must follow strict peer review through PRs with no direct pushes allowed, regardless of the submitters permission level.

**Comment by mdanter** [comment]
I completely agree with you that the workflow should not change. As far as I know I'm not going anywhere, and neither does my github handle, I use this for private and work related projects for Red Hat Jboss Middleware ;). I'm also of the mindset that if something isn't broken, there's no need to fix it. All that said, I'm absolutely open to moving this to an org if the fine contributors think that would be beneficial. Also, let me say that all of you have done an amazing job of making the codebase much cleaner then it was when I initially wrote it. Thank you for that! I'm really happy to see that this library has proven to be useful!

**Comment by mdanter** [comment]
I created the phpecc github org a few minutes ago, forked the current codebase, and designated @btcdrak an admin. It's there if we would like to use it, I'm certainly not mandating it.

**Comment by btcdrak** [comment]
It's a simple matter of using "Transfer Ownership" from https://github.com/mdanter/phpecc/settings

**Comment by btcdrak** [comment]
@afk11 @aztech-dev what do you think? Should we move it? It's probably a good idea overall.

**Comment by btcdrak** [comment]
@mdanter In order to preserve everything you need to delete the fork phpecc/phpecc then transfer ownership from mdanter/phpecc to the new org. That will move all tickets, PRs etc to the new location and setup redirection.

**Comment by aztech-dev** [comment]
I don't really care actually :) But if you consider the "hit by a bus" factor, then yes, it's a good idea.

**Comment by mdanter** [comment]
this is done.

**Comment by btcdrak** [comment]
I've updated packagist too.
